image: go1.2
env:
  - GOROOT=/usr/lib/go
  - GOPATH=$PWD/Godeps/_workspace:/var/cache/drone
  - PATH=$PWD/Godeps/_workspace/bin:/var/cache/drone/bin:$PATH
script:
  - sudo apt-get -y install libsqlite3-dev sqlite3 1> /dev/null 2> /dev/null
  - make embed
  - make build-dist
  - make test
  - make dpkg
notify:
  email:
    recipients:
      - brad@drone.io

publish:
  s3:
    acl: public-read
    region: us-east-1
    bucket: downloads.drone.io
    access_key: $AWS_KEY
    secret_key: $AWS_SECRET
    source: deb/drone.deb
    target: latest/
